[package]
name = "tun"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Pangolin tunnel node (tun) — connects to ngx, proxies customer traffic"

[[bin]]
name = "tun"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
thiserror.workspace = true
clap.workspace = true
chrono.workspace = true
reqwest = { version = "0.13.4", features = ["json"] }
rmp-serde.workspace = true
pangolin-core = { version = "0.2.0", path = "../pangolin-core" }
flate2.workspace = true
http = "1.4.1"
url = "2.5.8"
