//! Admin UI asset pipeline.
//!
//! Assets in the repo-root `assets/` directory are snapshotted by
//! [`rust-embed`] at compile time (release) or read from the filesystem at
//! runtime (`debug-embed` feature, dev builds).
//!
//! ## Build pipeline
//!
//! Single source of truth lives in [`assets/`] at the repo root:
//!
//! - `tailwindcss.css` (tracked) — Tailwind CLI input with `@tailwind` directives
//! - `app.js`           (tracked) — hand-written JS source, no imports
//! - `app.css` (gitignored) — Tailwind CLI output. Unminified in dev (regenerated by `make build-ui`), minified inside the Docker `builder` stage.
//!
//! [`assets/app.js`] is the only JS bundle. The Docker `builder` stage runs
//! `esbuild --bundle --minify --outfile=./assets/app.js`, which overwrites
//! the source with the minified bundle before `cargo build --release`
//! snapshots it into the binary. The binary always serves `app.js` — no
//! `app.min.js` file, no `PANGOLIN_ADMIN_JS` switch.
//!
//! [`assets/`]: https://github.com/yaitoo/pangolin/tree/main/assets
//! [`assets/app.js`]: https://github.com/yaitoo/pangolin/blob/main/assets/app.js
//!
//! ## Hashing
//!
//! Hashes are computed once at startup from the served bytes, so the
//! `?v=<hash>` URL stays in lockstep with the response body — a hash change
//! produces a new URL and a guaranteed browser-cache miss; no 304 round-trip.

use std::sync::LazyLock;

use rust_embed::Embed;
use sha2::{Digest, Sha256};

/// Snapshot of every file in the repo-root `assets/` directory.
///
/// `#[folder]` is resolved relative to `CARGO_MANIFEST_DIR`
/// (`crates/admin/`), so `../../assets/` lands at the repo root — the single
/// source of truth shared by `make build-ui` and the Docker `builder` stage.
///
/// - **Release**: bytes are embedded into the binary.
/// - **Debug** (`debug-embed`): `Asset::get()` reads from the filesystem at
///   runtime, so `make build-ui` takes effect on the next process restart.
#[derive(Embed)]
#[folder = "../../assets/"]
pub struct Asset;

/// Filename of the JS bundle served to the browser. Always `app.js` — in dev
/// it's the raw source, in production the Docker `builder` stage overwrites
/// it with the minified esbuild bundle (see module docs).
pub const JS_FILE: &str = "app.js";

/// Length (in hex chars) of the cache-bust token. 48 bits is enough that
/// accidental collisions are negligible for a small admin bundle.
const SHORT_HASH_LEN: usize = 12;

/// CSS bundle content hash, computed from `app.css`. First 12 hex chars of
/// the SHA-256 digest.
pub static CSS_HASH: LazyLock<String> = LazyLock::new(|| short_hash("app.css"));

/// JS bundle content hash, computed from `app.js` (the file the binary serves).
pub static JS_HASH: LazyLock<String> = LazyLock::new(|| short_hash(JS_FILE));

/// Bytes of the CSS bundle. Empty `Vec` on miss; the unstyled page surfaces
/// a broken build loudly enough.
pub fn css_bytes() -> Vec<u8> {
    <Asset as rust_embed::RustEmbed>::get("app.css")
        .map(|f| f.data.into_owned())
        .unwrap_or_default()
}

/// Bytes of the JS bundle (`app.js`). See module docs for how this file's
/// contents differ between dev (raw source) and production (Docker-overwritten
/// minified bundle).
pub fn js_bytes() -> Vec<u8> {
    <Asset as rust_embed::RustEmbed>::get(JS_FILE)
        .map(|f| f.data.into_owned())
        .unwrap_or_default()
}

pub const CSS_MIME: &str = "text/css; charset=utf-8";
pub const JS_MIME: &str = "application/javascript; charset=utf-8";
/// `Cache-Control` for fingerprinted assets. Paired with `?v=<hash>` URLs,
/// the "hash change → new URL" contract makes one-year immutable caching safe.
pub const IMMUTABLE_CACHE: &str = "public, max-age=31536000, immutable";

/// Compute the SHA-256 digest of the embedded file and return the first
/// [`SHORT_HASH_LEN`] hex chars.
fn short_hash(name: &str) -> String {
    let Some(file) = <Asset as rust_embed::RustEmbed>::get(name) else {
        log::warn!(
            "admin assets: no embedded file for {}, hash will be empty",
            name
        );
        return String::new();
    };
    let digest = Sha256::digest(&file.data);
    hex::encode(&digest[..SHORT_HASH_LEN / 2])
}
